### ISSUE TITLE
does not work if input is between <form> </form>

### ISSUE THREAD

**Issue by kanpro** [joshua-s/jquery.nice-number#1]
FYI: utility is great but when input field is sandwiched between form tags, it will not increment

<form>
<h1>jQuery Nice Number Plugin Demo</h1>
<input type="number" value="1000">
</div>
</form>

**Comment by joshua-s** [comment]
@kanpro thank you for reporting this issue. I am investigating it

**Comment by kanpro** [comment]
awesome response than you so much


-------- Original Message --------
Subject: Re: [joshua-s/jquery.nice-number] does not work if input is
between <form> </form> (#1)

**Comment by joshua-s** [comment]
@kanpro I published the fix on npm :)

Thanks again!
