### ISSUE TITLE
several nice numbers

### ISSUE THREAD

**Issue by ATM-NET** [joshua-s/jquery.nice-number#3]
How to create some nice numbers in sequence? 
Every time I add a new input, I must to initialize the plugin again and then I see that the number of +/- buttons is increasing:

![_screenshot 2019-10-27 в 21 18 17](https://user-images.githubusercontent.com/42110592/67637834-484f8d00-f900-11e9-92e7-bc76b7b7fabc.JPG)

**Comment by joshua-s** [comment]
Hey @ATM-NET thank you for reporting this issue and I apologize for the delay. I will get around to patching this soon!

**Comment by joshua-s** [comment]
I have added a potential fix and will be testing it

**Comment by ATM-NET** [comment]
Yep, it is really nice =)
