### ISSUE TITLE
Something like onIncreased and onDecreased method ?

### ISSUE THREAD

**Issue by boypanjaitan16** [joshua-s/jquery.nice-number#6]
I need to do something on increasing or decreasing the value? any idea with this ?

**Comment by frankie-tech** [comment]
@boypanjaitan16 If you still need something for callbacks you can use/modify what I have on my branch.

If you don't wanna mess around with other peoples forks and branches, you could also listen for the `input` event on the number input like this:

```js
var lastValue = 0;
var $input = $('#myInput');
$input.niceNumber();

$input.on('input', function(event) {
	if ($input.value > lastValue) {
		console.log("I've incremented!");
	} else {
		console.log("I've decremented!");
	}
	lastValue = $input.value;
})

```

Hope that helps! 🙂

**Comment by joshua-s** [comment]
This has been added by @frankie-tech 🎉 in #7! The updates are now released to NPM and GitHub Packages.

Thanks for the suggestion @boypanjaitan16
